name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build with MSBuild
        run: msbuild .\Server\Server.sln /p:Configuration=Release /p:Platform=x64
      - name: List build output
        run: dir "Server\x64\Release"
